-- Code Academy Platform - database schema
-- Run this once in the Supabase SQL editor (Project -> SQL Editor -> New query).

create extension if not exists "pgcrypto";

-- ---------- Trainers (teachers) ----------
create table if not exists trainers (
  id uuid primary key default gen_random_uuid(),
  username text unique not null,
  password_hash text not null,
  display_name text not null,
  is_owner boolean not null default false, -- true only for the founding trainer (Yaseen)
  created_at timestamptz not null default now()
);

-- ---------- Courses ----------
create table if not exists courses (
  id uuid primary key default gen_random_uuid(),
  trainer_id uuid references trainers(id) on delete set null,
  title text not null,
  description text default '',
  price numeric not null default 750,
  cover_color text default '#F0A93C', -- accent color for the course card
  published boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------- Lessons (each lesson = up to 4 video parts, 30-45 min each) ----------
create table if not exists lessons (
  id uuid primary key default gen_random_uuid(),
  course_id uuid references courses(id) on delete cascade,
  title text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- ---------- Lesson video parts ----------
create table if not exists lesson_parts (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid references lessons(id) on delete cascade,
  part_number integer not null check (part_number between 1 and 4),
  title text not null default '',
  video_url text, -- external embeddable link (YouTube unlisted / Drive / Vimeo)
  duration_minutes integer not null default 30 check (duration_minutes <= 45),
  created_at timestamptz not null default now(),
  unique (lesson_id, part_number)
);

-- ---------- Access codes generated by a trainer ----------
create table if not exists access_codes (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  course_id uuid references courses(id) on delete cascade,
  trainer_id uuid references trainers(id) on delete set null,
  batch_label text, -- e.g. "batch of 500 generated on ..."
  used_by_student uuid, -- filled in once a student registers with it
  created_at timestamptz not null default now()
);

-- ---------- Students ----------
create table if not exists students (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  access_code text not null, -- the code the student logs in with (their "password")
  created_at timestamptz not null default now()
);

-- ---------- A student's enrollment in one course (a student can enroll in many) ----------
create table if not exists enrollments (
  id uuid primary key default gen_random_uuid(),
  student_id uuid references students(id) on delete cascade,
  course_id uuid references courses(id) on delete cascade,
  access_code_id uuid references access_codes(id) on delete set null,
  enrolled_at timestamptz not null default now(),
  unique (student_id, course_id)
);

-- ---------- Video view tracking (max 3 views per student per lesson part) ----------
create table if not exists video_views (
  id uuid primary key default gen_random_uuid(),
  student_id uuid references students(id) on delete cascade,
  lesson_part_id uuid references lesson_parts(id) on delete cascade,
  view_count integer not null default 0,
  last_viewed_at timestamptz,
  unique (student_id, lesson_part_id)
);

-- ---------- Exams (one per lesson) ----------
create table if not exists exams (
  id uuid primary key default gen_random_uuid(),
  lesson_id uuid references lessons(id) on delete cascade,
  title text not null default 'Lesson exam'
);

create table if not exists exam_questions (
  id uuid primary key default gen_random_uuid(),
  exam_id uuid references exams(id) on delete cascade,
  question_text text not null,
  options jsonb not null, -- ["A ...", "B ...", "C ...", "D ..."]
  correct_index integer not null,
  sort_order integer not null default 0
);

-- ---------- Exam attempts (max 2 attempts per student per exam) ----------
create table if not exists exam_attempts (
  id uuid primary key default gen_random_uuid(),
  student_id uuid references students(id) on delete cascade,
  exam_id uuid references exams(id) on delete cascade,
  attempt_number integer not null,
  score numeric not null,
  total_questions integer not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_lessons_course on lessons(course_id);
create index if not exists idx_lesson_parts_lesson on lesson_parts(lesson_id);
create index if not exists idx_access_codes_course on access_codes(course_id);
create index if not exists idx_enrollments_student on enrollments(student_id);
create index if not exists idx_enrollments_course on enrollments(course_id);
create index if not exists idx_exam_questions_exam on exam_questions(exam_id);
create index if not exists idx_exam_attempts_student_exam on exam_attempts(student_id, exam_id);
